---
- name: Install PowerDNS
  hosts: powerdns

  pre_tasks:

    - name: apt-get update
      ansible.builtin.apt:
        pkg:
          - mariadb-server
          - python3-mysqldb
          - mariadb-client
        update_cache: yes

    - name: Get MySQL version with non-default credentials
      failed_when: false
      register: file_ck
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ powerdns_mysql_root_password }}"
        filter: version

    - debug:
       var: file_ck

    - name: Change the authentication plugin of MySQL root user to mysql_native_password
      when: file_ck.failed is true
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

    - name: Flush Privileges
      when: file_ck.failed is true
      shell: mysql -u root -e 'FLUSH PRIVILEGES'

    - name: Set mariadb root Password
      when: file_ck.rc is true
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ powerdns_mysql_root_password }}'
        state: present 

  roles:
    - role: powerdns.pdns
      pdns_user: "root"
      pdns_group: "root"
      pdns_mysql_packages:
        - mariadb-client
        - python3-mysqldb
