---
- name: Install PowerDNS
  hosts: powerdns

  pre_tasks:
    - name: apt-get update
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - role: powerdns.pdns
      pdns_mysql_packages:
        - mariadb-server
        - mariadb-client
        - python3-mysqldb
