---
- name: Install PowerDNS
  hosts: powerdns
  pre_tasks:
    - name: Install mariadb
      ansible.builtin.package:
        name: 
         - mariadb-server
         - mariadb-client
        state: present
  roles:
    - { role: powerdns.pdns }
