---
- name: Install PowerDNS
  hosts: powerdns

  pre_tasks:
    - import_tasks: install_mariadb.yaml

  roles:
    - { role: powerdns.pdns , pdns_mysql_packages: [mariadb-client] }
    - { role: powerdns.pdns_recursor }
    - { role: geerlingguy.docker }

  post_tasks:
    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        virtualenv: /opt/powerdns
        virtualenv_python: python3
        name:
          - requests==2.29.0
          - docker
          - docker-compose

    - name: PowerDNS-Admin
      vars:
        ansible_python_interpreter: /opt/powerdns/bin/python
      community.docker.docker_compose:
        project_name: powerdns-admin
        definition:
          version: "3"
          services:
            app:
              restart: always
              extra_hosts:
                - powerdns:host-gateway
              image: powerdnsadmin/pda-legacy:latest
              container_name: powerdns_admin
              ports:
                - "9191:80"
              logging:
                driver: json-file
                options:
                  max-size: 50m
              environment:
                - "SQLALCHEMY_DATABASE_URI=mysql://pdnsadminuser:{{ powerdns_admin_db_password }}@powerdns/powerdnsadmin"
                - "GUNICORN_TIMEOUT=60"
                - "GUNICORN_WORKERS=2"
                - "GUNICORN_LOGLEVEL=DEBUG"

    - name: Wait for port 9191 to become open on the host,
      ansible.builtin.wait_for:
        port: 9191
        timeout: 300
        delay: 10

    - name: Run several insert queries against db test_db in single transaction
      community.mysql.mysql_query:
        login_db: powerdnsadmin
        login_user: root
        login_password: "{{ powerdns_mysql_root_password }}"
        single_transaction: true
        query:
          -  INSERT IGNORE INTO `setting` 
            VALUES 
            (47,'pdns_api_url','http://powerdns:8081'),
            (48,'pdns_api_key', '{{ powerdns_api_key }}'),
            (49,'pdns_version','4.1.1');

          - INSERT IGNORE INTO `user` 
            VALUES 
            (1,'admin','{{ '%s' | format(powerdns_admin_db_password) | password_hash('bcrypt') }}','','','',NULL,1,0);

