---
- name: Install PowerDNS
  hosts: powerdns

  pre_tasks:

    - name: apt-get update
      ansible.builtin.apt:
        pkg:
          - mariadb-server
          - python3-mysqldb
          - mariadb-client
        update_cache: yes

    - name: Change the authentication plugin of MySQL root user to mysql_native_password
      shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

    - name: Flush Privileges
      shell: mysql -u root -e 'FLUSH PRIVILEGES'

    - name: Set mariadb root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ powerdns_mysql_root_password }}'
        state: present 

  roles:
    - role: powerdns.pdns
      pdns_mysql_packages:
        - mariadb-client
        - python3-mysqldb
