---
- name: Install PowerDNS
  hosts: powerdns
  pre_tasks:
    - name: update

    - name: Install mariadb
      ansible.builtin.apt:
        pkg: 
         - mariadb-server
         - mariadb-client
        state: present
        update_cache: yes
  roles:
    - { role: powerdns.pdns }
