---
roles:
  # Install a role from Ansible Galaxy.
  - name: powerdns.pdns
    version: v1.7.0
  - name: powerdns.pdns_recursor
    version: v1.6.0
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.pip
    version: 2.2.0
